global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["http://localhost:8005"]  # If app runs in Docker
        # or use ["localhost:8000"] if running FastAPI locally
