{
 "title": "FastAPI MLOps Monitoring",
 "tags": [
  "fastapi",
  "mlops"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Model Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_version" }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])" }
   ]
  },
  {
   "title": "Retrains Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "retrain_jobs_total" }
   ]
  },
  {
   "title": "Latency (avg ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m]) * 1000"
    }
   ]
  },
  {
   "title": "Predictions by Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (status) (rate(predictions_total[1m]))"
    }
   ]
  }
 ]
}